### ISSUE TITLE
About metrics

### ISSUE THREAD

**Issue by LaFeuilleMorte** [city-super/Octree-AnyGS#1]
Hi, thanks for opensource this work. Can you provide some metrics on the three kinds of GS algorithms you have used in your repo. For example, metrics (PSNR,SSIM, LPIPS) on (3DGS, Neural GS, 2DGS) with mipnerf360 dataset.

**Comment by tongji-rkr** [comment]
I will release it in the near two days. If you need ckpt of specific scenes, please mail me .

**Comment by tongji-rkr** [comment]
All results have been released to the README.
