### ISSUE TITLE
Inqury about data preparation

### ISSUE THREAD

**Issue by hebing-sjtu** [city-super/Octree-AnyGS#11]
First of all, thank you for your excellent work!

I am fascinated by the potential of Gaussians to represent large-scale scenes ([link to teaser image](https://github.com/city-super/Octree-AnyGS/raw/main/assets/teaser.png)). I'd like to capture the big scenario data myself and try to reconstruct it. I would greatly appreciate it if you could share your insights on preparing the training data.

Specifically:

How should the aircraft's flight path be designed to effectively capture images of the region?
Does the training process use all frames from the captured video or only a subset of evenly selected ones?
What preprocessing steps are required to obtain the downsampled data? Should the COLMAP method or lidar data be used?
If it's the COLMAP method, what is the GPU load during the preprocessing stage?
Will there be a way to do training and rendering with personal consumer GPUs such as the 24G RTX GeForce 4090?

Thank you in advance for your guidance!

**Comment by tongji-rkr** [comment]
1. I suggest you refer to the knowledge of oblique photography. I think a zigzag scan should be enough.
2. We typically have 1-3 frames per second.
3. You can downsample the image directly. Colmap and lidar are two pipelines. Each has its advantages and disadvantages.
4. COLMAP doesn't rely much on the GPU. But GPU is need.
5. Downsample the image to 1k or smaller.
