### ISSUE TITLE
Question about ScaffoldGS config

### ISSUE THREAD

**Issue by leblond14u** [city-super/Octree-AnyGS#12]
Hi, 

Thanks for your work.

I'm a bit confused with the config of scaffoldGS. 
There is no apparent **max_sh_degree** parameter in the config file.
 Is the **view_dim** the parameter the actual **max_sh_degree** one ?

Thanks in advance,
Best regards,

Hugo

**Comment by jianglh-WHU** [comment]
Well, scaffolds do not predict the sh attribute but instead predict color directly through an MLP.

**Comment by leblond14u** [comment]
Ok thank you very much
