### ISSUE TITLE
How to run with 2DGS

### ISSUE THREAD

**Issue by kke19** [city-super/Octree-AnyGS#2]
Thank you for your extraordinary project。
You mentioned that it can be extended to use with 2DGS. I would like to know how to run the 2DGS version of this.

**Comment by tongji-rkr** [comment]
https://github.com/city-super/Octree-AnyGS/blob/main/config/2dgs/base_model.yaml

**Comment by tongji-rkr** [comment]
Remember to install the `2dgs version` when installing `gsplat`.
