### ISSUE TITLE
Too large RAM consumption when setting data_device='cpu' .

### ISSUE THREAD

**Issue by LaFeuilleMorte** [city-super/Octree-AnyGS#3]
Hi, I'm trying to use large images to train GS model (8K resolution). To avoid CUDA OOM, I set data device to cpu. But only loading 220 images would drain my RAM memory (170GB). Is that normal?

**Comment by tongji-rkr** [comment]
This is normal, and if you store them in RAM it is not enough, you can store them in `.pt` files and maintain a certain number of image queues each time you train.
