### ISSUE TITLE
Large batch size for training

### ISSUE THREAD

**Issue by LaFeuilleMorte** [city-super/Octree-AnyGS#5]
Hi, I've read a recent work that can significantly enhance the performance of current GS algorithms. It's really simple. Just accumulate losses of multiple images and then backwards in total. For more details, you can reference to https://github.com/xiaobiaodu/MVGS

From my experiments, this simple measure can increase about 1 dB on PSNR.

**Comment by jianglh-WHU** [comment]
Thanks for your sincere suggestion!

**Comment by luckyday2022** [comment]
Is the strategy from https://github.com/xiaobiaodu/MVGS easy to integrate into this project? Could you please share the relevant code if available?
