### ISSUE TITLE
gsplat version issue

### ISSUE THREAD

**Issue by ljh12401** [city-super/Octree-AnyGS#9]
first of all, thank you for your excellent work!

Yet when i was configuring the environment, i found that the installation of gsplat always failed. I used the gsplat version you listed in the environment.yml, but when I switch the version to what you mentioned in the readme, it worked. I was wondering if there exists some bugs in the version of your gsplat.

thanks again.

**Comment by Reed-yang** [comment]
same, but `the version to what mentioned in the readme` seems doesn't support 2dgs?

**Comment by ljh12401** [comment]
> same, but `the version to what mentioned in the readme` seems doesn't support 2dgs?
https://github.com/FantasticOven2/gsplat this one? I have not tested it in 2dgs configuration, yet it works fine in scaffoldgs setup.

**Comment by tongji-rkr** [comment]
Please use this version (https://github.com/tongji-rkr/gsplat-2dgs), this is the bug-free version I am based on https://github.com/FantasticOven2/gsplat.

**Comment by tongji-rkr** [comment]
> same, but `the version to what mentioned in the readme` seems doesn't support 2dgs?

https://github.com/tongji-rkr/gsplat-2dgs
